export const ALL_TIMESHEETS = 'ALL_TIMESHEETS';
export const ALL_TIMESHEETS_SUCCESS = 'ALL_TIMESHEETS_SUCCESS';
export const ALL_TIMESHEETS_ERROR = 'ALL_TIMESHEETS_ERROR';

export const PROJECT_TIMESHEETS = 'PROJECT_TIMESHEETS';
export const PROJECT_TIMESHEETS_SUCCESS = 'PROJECT_TIMESHEETS_SUCCESS';
export const PROJECT_TIMESHEETS_ERROR = 'PROJECT_TIMESHEETS_ERROR';

export const TASKLIST_TASKS = 'TASKLIST_TASKS';
export const TASKLIST_TASKS_SUCCESS = 'TASKLIST_TASKS_SUCCESS';
export const TASKLIST_TASKS_ERROR = 'TASKLIST_TASKS_ERROR';

export const SUBTASKS = 'SUBTASKS';
export const SUBTASKS_SUCCESS = 'SUBTASKS_SUCCESS';
export const SUBTASKS_ERROR = 'SUBTASKS_ERROR';

export const TIME_STATUSES = 'TIME_STATUSES';
export const TIME_STATUSES_SUCCESS = 'TIME_STATUSES_SUCCESS';
export const TIME_STATUSES_ERROR = 'TIME_STATUSES_ERROR';

export const ADD_TIMESHEET = 'ADD_TIMESHEET';
export const ADD_TIMESHEET_SUCCESS = 'ADD_TIMESHEET_SUCCESS';
export const ADD_TIMESHEET_ERROR = 'ADD_TIMESHEET_ERROR';

export const ADD_TIME = 'ADD_TIME';
export const ADD_TIME_SUCCESS = 'ADD_TIME_SUCCESS';
export const ADD_TIME_ERROR = 'ADD_TIME_ERROR';


