export const ALL_EVENTS = 'ALL_EVENTS';
export const ALL_EVENTS_SUCCESS = 'ALL_EVENTS_SUCCESS';
export const ALL_EVENTS_ERROR = 'ALL_EVENTS_ERROR';

export const ALL_MILESTONES = 'ALL_MILESTONES';
export const ALL_MILESTONES_SUCCESS = 'ALL_MILESTONES_SUCCESS';
export const ALL_MILESTONES_ERROR = 'ALL_MILESTONES_ERROR';

export const PROJECT_EVENTS = 'PROJECT_EVENTS';
export const PROJECT_EVENTS_SUCCESS = 'PROJECT_EVENTS_SUCCESS';
export const PROJECT_EVENTS_ERROR = 'PROJECT_EVENTS_ERROR';

export const PROJECT_MILESTONES = 'PROJECT_MILESTONES';
export const PROJECT_MILESTONES_SUCCESS = 'PROJECT_MILESTONES_SUCCESS';
export const PROJECT_MILESTONES_ERROR = 'PROJECT_MILESTONES_ERROR';
