export const MY_PROJECTS = 'MY_PROJECTS';
export const MY_PROJECTS_SUCCESS = 'MY_PROJECTS_SUCCESS';
export const MY_PROJECTS_ERROR = 'MY_PROJECTS_ERROR';

export const MY_TASKS = 'MY_TASKS';
export const MY_TASKS_SUCCESS = 'MY_TASKS_SUCCESS';
export const MY_TASKS_ERROR = 'MY_TASKS_ERROR';

export const MY_EVENTS = 'MY_EVENTS';
export const MY_EVENTS_SUCCESS = 'MY_EVENTS_SUCCESS';
export const MY_EVENTS_ERROR = 'MY_EVENTS_ERROR';

export const MY_MILESTONES = 'MY_MILESTONES';
export const MY_MILESTONES_SUCCESS = 'MY_MILESTONES_SUCCESS';
export const MY_MILESTONES_ERROR = 'MY_MILESTONES_ERROR';

export const MY_ACTIVITIES = 'MY_ACTIVITIES';
export const MY_ACTIVITIES_SUCCESS = 'MY_ACTIVITIES_SUCCESS';
export const MY_ACTIVITIES_ERROR = 'MY_ACTIVITIES_ERROR';

export const MY_CALENDAR = 'MY_CALENDAR';
export const MY_CALENDAR_SUCCESS= 'MY_CALENDAR_SUCCESS';
export const MY_CALENDAR_ERROR = 'MY_CALENDAR_ERROR';

export const BOOKMARKS = 'BOOKMARKS';
export const BOOKMARKS_SUCCESS = 'BOOKMARKS_SUCCESS';
export const BOOKMARKS_ERROR = 'BOOKMARKS_ERROR';

export const QUICKIES = 'QUICKIES';
export const QUICKIES_SUCCESS = 'QUICKIES_SUCCESS';
export const QUICKIES_ERROR = 'QUICKIES_ERROR';






