export const ALL_TASKS = 'ALL_TASKS';
export const ALL_TASKS_SUCCESS = 'ALL_TASKS_SUCCESS';
export const ALL_TASKS_ERROR = 'ALL_TASKS_ERROR';

/////////////////////////////////////
export const TASKLISTS = 'TASKLISTS';
export const TASKLISTS_SUCCESS = 'TASKLISTS_SUCCESS';
export const TASKLISTS_ERROR = 'TASKLISTS_ERROR';

export const TASKS = 'TASKS';
export const TASKS_SUCCESS = 'TASKS_SUCCESS';
export const TASKS_ERROR = 'TASKS_ERROR';

export const TASKLISTS_TASKS = 'TASKLISTS_TASKS';
export const TASKLISTS_TASKS_SUCCESS = 'TASKLISTS_TASKS_SUCCESS';
export const TASKLISTS_TASKS_ERROR = 'TASKLISTS_TASKS_ERROR';

export const ADD_TASK = 'ADD_TASK';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_ERROR = 'ADD_TASK_ERROR';

export const ADD_TASK_ASSIGNEES = 'ADD_TASK_ASSIGNEES';
export const ADD_TASK_ASSIGNEES_SUCCESS = 'ADD_TASK_ASSIGNEES_SUCCESS';
export const ADD_TASK_ASSIGNEES_ERROR = 'ADD_TASK_ASSIGNEES_ERROR';

export const UPDATE_TASK = 'UPDATE_TASK';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const UPDATE_TASK_ERROR = 'UPDATE_TASK_ERROR';

export const ADD_SUB_TASK = 'ADD_SUB_TASK';
export const ADD_SUB_TASK_SUCCESS = 'ADD_SUB_TASK_SUCCESS';
export const ADD_SUB_TASK_ERROR = 'ADD_SUB_TASK_ERROR';

export const ADD_SUB_TASK_ASSIGNEES = 'ADD_SUB_TASK_ASSIGNEES';
export const ADD_SUB_TASK_ASSIGNEES_SUCCESS = 'ADD_SUB_TASK_ASSIGNEES_SUCCESS';
export const ADD_SUB_TASK_ASSIGNEES_ERROR = 'ADD_SUB_TASK_ASSIGNEES_ERROR';

export const TASK_PROGRESSES = 'TASK_PROGRESSES';
export const TASK_PROGRESSES_SUCCESS = 'TASK_PROGRESSES_SUCCESS';
export const TASK_PROGRESSES_ERROR = 'TASK_PROGRESSES_ERROR';

export const TASK_LABELS = 'TASK_LABELS';
export const TASK_LABELS_SUCCESS = 'TASK_LABELS_SUCCESS';
export const TASK_LABELS_ERROR = 'TASK_LABELS_ERROR';
