export const ALL_PROJECTS = 'ALL_PROJECTS';
export const ALL_PROJECTS_SUCCESS = 'ALL_PROJECTS_SUCCESS';
export const ALL_PROJECTS_ERROR = 'ALL_PROJECTS_ERROR';

export const PROJECT_CATEGORIES = 'PROJECT_CATEGORIES';
export const PROJECT_CATEGORIES_SUCCESS = 'PROJECT_CATEGORIES_SUCCESS';
export const PROJECT_CATEGORIES_ERROR = 'PROJECT_CATEGORIES_ERROR';
export const PROJECT_STATUSES = 'PROJECT_STATUSES'; 
export const PROJECT_STATUSES_SUCCESS = 'PROJECT_STATUSES_SUCCESS'; 
export const PROJECT_STATUSES_ERROR = 'PROJECT_STATUSES_ERROR';

export const USER_PERSONS = 'USER_PERSONS';
export const USER_PERSONS_SUCCESS = 'USER_PERSONS_SUCCESS';
export const USER_PERSONS_ERROR = 'USER_PERSONS_ERROR';

export const PROJECT_COLORS = 'PROJECT_COLORS';
export const PROJECT_COLORS_SUCCESS = 'PROJECT_COLORS_SUCCESS';
export const PROJECT_COLORS_ERROR = 'PROJECT_COLORS_ERROR';

export const PROJECT_ACCESS_ROLES = 'PROJECT_ACCESS_ROLES';
export const PROJECT_ACCESS_ROLES_SUCCESS = 'PROJECT_ACCESS_ROLES_SUCCESS';
export const PROJECT_ACCESS_ROLES_ERROR = 'PROJECT_ACCESS_ROLES_ERROR';

export const ADD_PROJECT = 'ADD_PROJECT';
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS';
export const ADD_PROJECT_ERROR = 'ADD_PROJECT_ERROR';

export const ADD_PROJECT_CATEGORY = 'ADD_PROJECT_CATEGORY';
export const ADD_PROJECT_CATEGORY_SUCCESS = 'ADD_PROJECT_CATEGORY_SUCCESS';
export const ADD_PROJECT_CATEGORY_ERROR = 'ADD_PROJECT_CATEGORY_ERROR';

export const ADD_PROJECT_STATUS = 'ADD_PROJECT_STATUS';
export const ADD_PROJECT_STATUS_SUCCESS = 'ADD_PROJECT_STATUS_SUCCESS';
export const ADD_PROJECT_STATUS_ERROR = 'ADD_PROJECT_STATUS_ERROR';

export const ADD_PROJECT_ASSIGNEES = 'ADD_PROJECT_ASSIGNEES';
export const ADD_PROJECT_ASSIGNEES_SUCCESS = 'ADD_PROJECT_ASSIGNEES_SUCCESS';
export const ADD_PROJECT_ASSIGNEES_ERROR = 'ADD_PROJECT_ASSIGNEES_ERROR';

export const INVITE_PERSON = 'INVITE_PERSON';
export const INVITE_PERSON_SUCCESS = 'INVITE_PERSON_SUCCESS';
export const INVITE_PERSON_ERROR = 'INVITE_PERSON_ERROR';


/////////////////////////////////////
export const PROJECT_LABELS = 'PROJECT_LABELS';
export const PROJECT_LABELS_SUCCESS = 'PROJECT_LABELS_SUCCESS';
export const PROJECT_LABELS_ERROR = 'PROJECT_LABELS_ERROR';

export const ADD_PROJECT_LABEL = 'ADD_PROJECT_LABEL';
export const ADD_PROJECT_LABEL_SUCCESS = 'ADD_PROJECT_LABEL_SUCCESS';
export const ADD_PROJECT_LABEL_ERROR = 'ADD_PROJECT_LABEL_ERROR';


